env:
  - GO111MODULE=on

builds:
  - id: qng
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    ldflags:
      - "-s -w"
    dir: "./cmd/qng"
    binary: qng

  - id: qx
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    ldflags:
      - "-s -w"
    dir: "./cmd/qx"
    binary: qx

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip