// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Qitmeer/qng/p2p/proto/v1/snapsync.proto

package qitmeer_p2p_v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Locator struct {
	Block                *Hash    `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Root                 *Hash    `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locator) Reset()         { *m = Locator{} }
func (m *Locator) String() string { return proto.CompactTextString(m) }
func (*Locator) ProtoMessage()    {}
func (*Locator) Descriptor() ([]byte, []int) {
	return fileDescriptor_55d540c020d195f7, []int{0}
}
func (m *Locator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Locator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Locator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Locator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locator.Merge(m, src)
}
func (m *Locator) XXX_Size() int {
	return m.Size()
}
func (m *Locator) XXX_DiscardUnknown() {
	xxx_messageInfo_Locator.DiscardUnknown(m)
}

var xxx_messageInfo_Locator proto.InternalMessageInfo

func (m *Locator) GetBlock() *Hash {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Locator) GetRoot() *Hash {
	if m != nil {
		return m.Root
	}
	return nil
}

type TransferData struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty" ssz-max:"1048576"`
	Stxos                []byte   `protobuf:"bytes,2,opt,name=stxos,proto3" json:"stxos,omitempty" ssz-max:"1048576"`
	DagBlock             []byte   `protobuf:"bytes,3,opt,name=dagBlock,proto3" json:"dagBlock,omitempty" ssz-max:"1048576"`
	Main                 bool     `protobuf:"varint,4,opt,name=main,proto3" json:"main,omitempty"`
	TokenState           []byte   `protobuf:"bytes,5,opt,name=tokenState,proto3" json:"tokenState,omitempty" ssz-max:"1048576"`
	PrevTSHash           *Hash    `protobuf:"bytes,6,opt,name=prevTSHash,proto3" json:"prevTSHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferData) Reset()         { *m = TransferData{} }
func (m *TransferData) String() string { return proto.CompactTextString(m) }
func (*TransferData) ProtoMessage()    {}
func (*TransferData) Descriptor() ([]byte, []int) {
	return fileDescriptor_55d540c020d195f7, []int{1}
}
func (m *TransferData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferData.Merge(m, src)
}
func (m *TransferData) XXX_Size() int {
	return m.Size()
}
func (m *TransferData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferData.DiscardUnknown(m)
}

var xxx_messageInfo_TransferData proto.InternalMessageInfo

func (m *TransferData) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *TransferData) GetStxos() []byte {
	if m != nil {
		return m.Stxos
	}
	return nil
}

func (m *TransferData) GetDagBlock() []byte {
	if m != nil {
		return m.DagBlock
	}
	return nil
}

func (m *TransferData) GetMain() bool {
	if m != nil {
		return m.Main
	}
	return false
}

func (m *TransferData) GetTokenState() []byte {
	if m != nil {
		return m.TokenState
	}
	return nil
}

func (m *TransferData) GetPrevTSHash() *Hash {
	if m != nil {
		return m.PrevTSHash
	}
	return nil
}

type SnapSyncReq struct {
	Target               *Locator   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Locator              []*Locator `protobuf:"bytes,2,rep,name=locator,proto3" json:"locator,omitempty" ssz-max:"32"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SnapSyncReq) Reset()         { *m = SnapSyncReq{} }
func (m *SnapSyncReq) String() string { return proto.CompactTextString(m) }
func (*SnapSyncReq) ProtoMessage()    {}
func (*SnapSyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_55d540c020d195f7, []int{2}
}
func (m *SnapSyncReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapSyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapSyncReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapSyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapSyncReq.Merge(m, src)
}
func (m *SnapSyncReq) XXX_Size() int {
	return m.Size()
}
func (m *SnapSyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapSyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SnapSyncReq proto.InternalMessageInfo

func (m *SnapSyncReq) GetTarget() *Locator {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SnapSyncReq) GetLocator() []*Locator {
	if m != nil {
		return m.Locator
	}
	return nil
}

type SnapSyncRsp struct {
	Target               *Locator        `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Evm                  *Hash           `protobuf:"bytes,2,opt,name=evm,proto3" json:"evm,omitempty"`
	Datas                []*TransferData `protobuf:"bytes,3,rep,name=datas,proto3" json:"datas,omitempty" ssz-max:"2000"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SnapSyncRsp) Reset()         { *m = SnapSyncRsp{} }
func (m *SnapSyncRsp) String() string { return proto.CompactTextString(m) }
func (*SnapSyncRsp) ProtoMessage()    {}
func (*SnapSyncRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_55d540c020d195f7, []int{3}
}
func (m *SnapSyncRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapSyncRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapSyncRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapSyncRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapSyncRsp.Merge(m, src)
}
func (m *SnapSyncRsp) XXX_Size() int {
	return m.Size()
}
func (m *SnapSyncRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapSyncRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SnapSyncRsp proto.InternalMessageInfo

func (m *SnapSyncRsp) GetTarget() *Locator {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SnapSyncRsp) GetEvm() *Hash {
	if m != nil {
		return m.Evm
	}
	return nil
}

func (m *SnapSyncRsp) GetDatas() []*TransferData {
	if m != nil {
		return m.Datas
	}
	return nil
}

func init() {
	proto.RegisterType((*Locator)(nil), "qitmeer.p2p.v1.Locator")
	proto.RegisterType((*TransferData)(nil), "qitmeer.p2p.v1.TransferData")
	proto.RegisterType((*SnapSyncReq)(nil), "qitmeer.p2p.v1.SnapSyncReq")
	proto.RegisterType((*SnapSyncRsp)(nil), "qitmeer.p2p.v1.SnapSyncRsp")
}

func init() {
	proto.RegisterFile("github.com/Qitmeer/qng/p2p/proto/v1/snapsync.proto", fileDescriptor_55d540c020d195f7)
}

var fileDescriptor_55d540c020d195f7 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0x71, 0x1c, 0xa7, 0xd5, 0x6b, 0x54, 0x95, 0x11, 0x08, 0xab, 0x42, 0x4e, 0x34, 0x0b,
	0x14, 0x51, 0xe1, 0x7f, 0x6d, 0x01, 0xb1, 0x34, 0x08, 0xb1, 0x60, 0x83, 0xdd, 0x3d, 0x9a, 0xb8,
	0x83, 0x1b, 0xb5, 0x9e, 0x99, 0xcc, 0x0c, 0x56, 0xcb, 0x96, 0x4b, 0xb0, 0xe0, 0x0c, 0x9c, 0x83,
	0x25, 0x27, 0x88, 0x50, 0xb8, 0x41, 0x4e, 0x80, 0x3a, 0x4e, 0x22, 0x13, 0x09, 0x2b, 0xdd, 0x8d,
	0x9e, 0x7e, 0xdf, 0xf7, 0xbe, 0x37, 0xef, 0x41, 0x5c, 0x4c, 0xf4, 0xc5, 0xe7, 0xb1, 0x9f, 0xf3,
	0x32, 0xf8, 0x30, 0xd1, 0x25, 0xa5, 0x32, 0x98, 0xb2, 0x22, 0x10, 0xb1, 0x08, 0x84, 0xe4, 0x9a,
	0x07, 0x55, 0x14, 0x28, 0x46, 0x84, 0xba, 0x61, 0xb9, 0x6f, 0x2a, 0x68, 0x7f, 0x5a, 0x83, 0xbe,
	0x88, 0x85, 0x5f, 0x45, 0x87, 0xfe, 0x36, 0x1e, 0x05, 0x2f, 0x78, 0xad, 0x3f, 0x8c, 0xb6, 0xe1,
	0x4b, 0xaa, 0x14, 0x29, 0x68, 0x2d, 0xc1, 0x1f, 0x61, 0xe7, 0x3d, 0xcf, 0x89, 0xe6, 0x12, 0x3d,
	0x05, 0x67, 0x7c, 0xc5, 0xf3, 0x4b, 0xd7, 0x1a, 0x5a, 0xa3, 0xbd, 0xf8, 0x81, 0xff, 0x6f, 0x1a,
	0xff, 0x1d, 0x51, 0x17, 0x69, 0x8d, 0xa0, 0x11, 0x74, 0x25, 0xe7, 0xda, 0xed, 0xb4, 0xa0, 0x86,
	0xc0, 0xdf, 0x3b, 0xd0, 0x3f, 0x93, 0x84, 0xa9, 0x4f, 0x54, 0xbe, 0x21, 0x9a, 0xa0, 0xa3, 0x66,
	0x9b, 0x7e, 0xf2, 0x70, 0x31, 0x1b, 0xdc, 0x57, 0xea, 0xcb, 0xb3, 0x92, 0x5c, 0xbf, 0xc2, 0x51,
	0x78, 0xf2, 0xf2, 0xf4, 0xc5, 0x73, 0xbc, 0xea, 0x73, 0x04, 0x8e, 0xd2, 0xd7, 0x5c, 0x99, 0x46,
	0xff, 0x87, 0x0d, 0x83, 0x22, 0xd8, 0x3d, 0x27, 0x45, 0x62, 0xcc, 0xed, 0x36, 0x7e, 0x8d, 0x21,
	0x04, 0xdd, 0x92, 0x4c, 0x98, 0xdb, 0x1d, 0x5a, 0xa3, 0xdd, 0xd4, 0xbc, 0xd1, 0x29, 0x80, 0xe6,
	0x97, 0x94, 0x65, 0x9a, 0x68, 0xea, 0x3a, 0x6d, 0x46, 0x0d, 0x10, 0x9d, 0x00, 0x08, 0x49, 0xab,
	0xb3, 0xec, 0x76, 0x78, 0xb7, 0xd7, 0xf2, 0x31, 0x0d, 0x0e, 0x7f, 0xb5, 0x60, 0x2f, 0x63, 0x44,
	0x64, 0x37, 0x2c, 0x4f, 0xe9, 0x14, 0x05, 0xd0, 0xd3, 0x44, 0x16, 0x54, 0x2f, 0xb7, 0xf0, 0x68,
	0xd3, 0x61, 0xb9, 0xad, 0x74, 0x89, 0xa1, 0xd7, 0xb0, 0x73, 0x55, 0x97, 0xdc, 0xce, 0xd0, 0x6e,
	0x51, 0x24, 0x07, 0x8b, 0xd9, 0xa0, 0xbf, 0x9e, 0xe1, 0x38, 0xc6, 0xe9, 0x4a, 0x89, 0x7f, 0x34,
	0x53, 0x28, 0x71, 0xf7, 0x14, 0x4f, 0xc0, 0xa6, 0x55, 0xd9, 0x7a, 0x0e, 0xb7, 0x00, 0x7a, 0x0b,
	0xce, 0x39, 0xd1, 0x44, 0xb9, 0xb6, 0xc9, 0xfa, 0x78, 0x93, 0x6c, 0x5e, 0x4a, 0x82, 0x16, 0xb3,
	0xc1, 0xfe, 0x3a, 0x70, 0x1c, 0x86, 0x21, 0x4e, 0x6b, 0x79, 0x72, 0xf0, 0x73, 0xee, 0x59, 0xbf,
	0xe6, 0x9e, 0xf5, 0x7b, 0xee, 0x59, 0xdf, 0xfe, 0x78, 0xf7, 0xc6, 0x3d, 0x73, 0xcf, 0xc7, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xf3, 0xd6, 0xbc, 0x78, 0x03, 0x00, 0x00,
}

func (m *Locator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Locator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Locator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Root != nil {
		{
			size, err := m.Root.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TransferData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PrevTSHash != nil {
		{
			size, err := m.PrevTSHash.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.TokenState) > 0 {
		i -= len(m.TokenState)
		copy(dAtA[i:], m.TokenState)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.TokenState)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Main {
		i--
		if m.Main {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.DagBlock) > 0 {
		i -= len(m.DagBlock)
		copy(dAtA[i:], m.DagBlock)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.DagBlock)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Stxos) > 0 {
		i -= len(m.Stxos)
		copy(dAtA[i:], m.Stxos)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.Stxos)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Block) > 0 {
		i -= len(m.Block)
		copy(dAtA[i:], m.Block)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.Block)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapSyncReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapSyncReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapSyncReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Locator) > 0 {
		for iNdEx := len(m.Locator) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locator[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Target != nil {
		{
			size, err := m.Target.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapSyncRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapSyncRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapSyncRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Datas) > 0 {
		for iNdEx := len(m.Datas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Datas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Evm != nil {
		{
			size, err := m.Evm.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Target != nil {
		{
			size, err := m.Target.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSnapsync(dAtA []byte, offset int, v uint64) int {
	offset -= sovSnapsync(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Locator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.Root != nil {
		l = m.Root.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TransferData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Block)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	l = len(m.Stxos)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	l = len(m.DagBlock)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.Main {
		n += 2
	}
	l = len(m.TokenState)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.PrevTSHash != nil {
		l = m.PrevTSHash.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SnapSyncReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Target != nil {
		l = m.Target.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if len(m.Locator) > 0 {
		for _, e := range m.Locator {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SnapSyncRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Target != nil {
		l = m.Target.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.Evm != nil {
		l = m.Evm.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if len(m.Datas) > 0 {
		for _, e := range m.Datas {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSnapsync(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSnapsync(x uint64) (n int) {
	return sovSnapsync(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Locator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Locator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Locator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &Hash{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Root == nil {
				m.Root = &Hash{}
			}
			if err := m.Root.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Block = append(m.Block[:0], dAtA[iNdEx:postIndex]...)
			if m.Block == nil {
				m.Block = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stxos", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stxos = append(m.Stxos[:0], dAtA[iNdEx:postIndex]...)
			if m.Stxos == nil {
				m.Stxos = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DagBlock", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DagBlock = append(m.DagBlock[:0], dAtA[iNdEx:postIndex]...)
			if m.DagBlock == nil {
				m.DagBlock = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Main", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Main = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenState", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenState = append(m.TokenState[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenState == nil {
				m.TokenState = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevTSHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PrevTSHash == nil {
				m.PrevTSHash = &Hash{}
			}
			if err := m.PrevTSHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapSyncReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapSyncReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapSyncReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Target == nil {
				m.Target = &Locator{}
			}
			if err := m.Target.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locator = append(m.Locator, &Locator{})
			if err := m.Locator[len(m.Locator)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapSyncRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapSyncRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapSyncRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Target == nil {
				m.Target = &Locator{}
			}
			if err := m.Target.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evm == nil {
				m.Evm = &Hash{}
			}
			if err := m.Evm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Datas = append(m.Datas, &TransferData{})
			if err := m.Datas[len(m.Datas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSnapsync(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSnapsync
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSnapsync
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSnapsync
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSnapsync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSnapsync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSnapsync = fmt.Errorf("proto: unexpected end of group")
)
