// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: snapsync.proto

package qitmeer_p2p_v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapSyncReq struct {
	TargetBlock          *Hash             `protobuf:"bytes,1,opt,name=targetBlock,proto3" json:"targetBlock,omitempty"`
	StateRoot            *Hash             `protobuf:"bytes,2,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	Locator              []*Locator        `protobuf:"bytes,3,rep,name=locator,proto3" json:"locator,omitempty" ssz-max:"32"`
	Status               []*TransferStatus `protobuf:"bytes,4,rep,name=status,proto3" json:"status,omitempty" ssz-max:"8"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SnapSyncReq) Reset()         { *m = SnapSyncReq{} }
func (m *SnapSyncReq) String() string { return proto.CompactTextString(m) }
func (*SnapSyncReq) ProtoMessage()    {}
func (*SnapSyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c7ae889115bb49, []int{0}
}
func (m *SnapSyncReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapSyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapSyncReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapSyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapSyncReq.Merge(m, src)
}
func (m *SnapSyncReq) XXX_Size() int {
	return m.Size()
}
func (m *SnapSyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapSyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SnapSyncReq proto.InternalMessageInfo

func (m *SnapSyncReq) GetTargetBlock() *Hash {
	if m != nil {
		return m.TargetBlock
	}
	return nil
}

func (m *SnapSyncReq) GetStateRoot() *Hash {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *SnapSyncReq) GetLocator() []*Locator {
	if m != nil {
		return m.Locator
	}
	return nil
}

func (m *SnapSyncReq) GetStatus() []*TransferStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SnapSyncRsp struct {
	TargetBlock          *Hash             `protobuf:"bytes,1,opt,name=targetBlock,proto3" json:"targetBlock,omitempty"`
	StateRoot            *Hash             `protobuf:"bytes,2,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	Status               []*TransferStatus `protobuf:"bytes,3,rep,name=status,proto3" json:"status,omitempty" ssz-max:"8"`
	Datas                []*TransferData   `protobuf:"bytes,4,rep,name=datas,proto3" json:"datas,omitempty" ssz-max:"262144"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SnapSyncRsp) Reset()         { *m = SnapSyncRsp{} }
func (m *SnapSyncRsp) String() string { return proto.CompactTextString(m) }
func (*SnapSyncRsp) ProtoMessage()    {}
func (*SnapSyncRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c7ae889115bb49, []int{1}
}
func (m *SnapSyncRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SnapSyncRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SnapSyncRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SnapSyncRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapSyncRsp.Merge(m, src)
}
func (m *SnapSyncRsp) XXX_Size() int {
	return m.Size()
}
func (m *SnapSyncRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapSyncRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SnapSyncRsp proto.InternalMessageInfo

func (m *SnapSyncRsp) GetTargetBlock() *Hash {
	if m != nil {
		return m.TargetBlock
	}
	return nil
}

func (m *SnapSyncRsp) GetStateRoot() *Hash {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *SnapSyncRsp) GetStatus() []*TransferStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SnapSyncRsp) GetDatas() []*TransferData {
	if m != nil {
		return m.Datas
	}
	return nil
}

type Locator struct {
	Block                *Hash    `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	StateRoot            *Hash    `protobuf:"bytes,2,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locator) Reset()         { *m = Locator{} }
func (m *Locator) String() string { return proto.CompactTextString(m) }
func (*Locator) ProtoMessage()    {}
func (*Locator) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c7ae889115bb49, []int{2}
}
func (m *Locator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Locator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Locator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Locator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locator.Merge(m, src)
}
func (m *Locator) XXX_Size() int {
	return m.Size()
}
func (m *Locator) XXX_DiscardUnknown() {
	xxx_messageInfo_Locator.DiscardUnknown(m)
}

var xxx_messageInfo_Locator proto.InternalMessageInfo

func (m *Locator) GetBlock() *Hash {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Locator) GetStateRoot() *Hash {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

type TransferStatus struct {
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Num                  uint32   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Total                uint64   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferStatus) Reset()         { *m = TransferStatus{} }
func (m *TransferStatus) String() string { return proto.CompactTextString(m) }
func (*TransferStatus) ProtoMessage()    {}
func (*TransferStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c7ae889115bb49, []int{3}
}
func (m *TransferStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferStatus.Merge(m, src)
}
func (m *TransferStatus) XXX_Size() int {
	return m.Size()
}
func (m *TransferStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TransferStatus proto.InternalMessageInfo

func (m *TransferStatus) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TransferStatus) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *TransferStatus) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type TransferData struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" ssz-max:"1048576"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" ssz-max:"1048576"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferData) Reset()         { *m = TransferData{} }
func (m *TransferData) String() string { return proto.CompactTextString(m) }
func (*TransferData) ProtoMessage()    {}
func (*TransferData) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c7ae889115bb49, []int{4}
}
func (m *TransferData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransferData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransferData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransferData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferData.Merge(m, src)
}
func (m *TransferData) XXX_Size() int {
	return m.Size()
}
func (m *TransferData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferData.DiscardUnknown(m)
}

var xxx_messageInfo_TransferData proto.InternalMessageInfo

func (m *TransferData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TransferData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SnapSyncReq)(nil), "qitmeer.p2p.v1.SnapSyncReq")
	proto.RegisterType((*SnapSyncRsp)(nil), "qitmeer.p2p.v1.SnapSyncRsp")
	proto.RegisterType((*Locator)(nil), "qitmeer.p2p.v1.Locator")
	proto.RegisterType((*TransferStatus)(nil), "qitmeer.p2p.v1.TransferStatus")
	proto.RegisterType((*TransferData)(nil), "qitmeer.p2p.v1.TransferData")
}

func init() { proto.RegisterFile("snapsync.proto", fileDescriptor_22c7ae889115bb49) }

var fileDescriptor_22c7ae889115bb49 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x41, 0x6e, 0xd3, 0x40,
	0x18, 0x85, 0x71, 0x9d, 0xb4, 0x62, 0x9c, 0x06, 0x33, 0x0a, 0xc2, 0xaa, 0x90, 0x1d, 0xcd, 0x86,
	0x08, 0x54, 0x97, 0xb8, 0x21, 0x54, 0x2c, 0x0d, 0x12, 0x5d, 0x20, 0x16, 0x13, 0x2e, 0xf0, 0xdb,
	0x9d, 0xba, 0x51, 0x6d, 0x8f, 0xeb, 0x19, 0x57, 0x84, 0x0b, 0xb0, 0xe1, 0x00, 0x1c, 0x89, 0x25,
	0x27, 0xb0, 0x50, 0xb8, 0x81, 0x4f, 0x80, 0x3c, 0xd3, 0xa6, 0x69, 0xa5, 0x82, 0x04, 0x52, 0x77,
	0xf3, 0xe4, 0xef, 0xbd, 0x5f, 0xef, 0x49, 0x46, 0x7d, 0x91, 0x43, 0x21, 0x16, 0x79, 0xec, 0x17,
	0x25, 0x97, 0x1c, 0xf7, 0xcf, 0xe6, 0x32, 0x63, 0xac, 0xf4, 0x8b, 0xa0, 0xf0, 0xcf, 0xc7, 0x3b,
	0xbb, 0xc9, 0x5c, 0x9e, 0x54, 0x91, 0x1f, 0xf3, 0x6c, 0x2f, 0xe1, 0x09, 0xdf, 0x53, 0x58, 0x54,
	0x1d, 0x2b, 0xa5, 0x84, 0x7a, 0x69, 0xfb, 0xce, 0x76, 0xc6, 0x84, 0x80, 0x84, 0x69, 0x49, 0xbe,
	0x6c, 0x20, 0x6b, 0x96, 0x43, 0x31, 0x5b, 0xe4, 0x31, 0x65, 0x67, 0x78, 0x8a, 0x2c, 0x09, 0x65,
	0xc2, 0x64, 0x98, 0xf2, 0xf8, 0xd4, 0x31, 0x86, 0xc6, 0xc8, 0x0a, 0x06, 0xfe, 0xf5, 0x9b, 0xfe,
	0x21, 0x88, 0x13, 0xba, 0x0e, 0xe2, 0x00, 0xdd, 0x17, 0x12, 0x24, 0xa3, 0x9c, 0x4b, 0x67, 0xe3,
	0x0f, 0xae, 0x2b, 0x0c, 0xbf, 0x41, 0x5b, 0x29, 0x8f, 0x41, 0xf2, 0xd2, 0x31, 0x87, 0xe6, 0xc8,
	0x0a, 0x1e, 0xdf, 0x74, 0xbc, 0xd7, 0x9f, 0x43, 0xbb, 0xa9, 0xbd, 0x9e, 0x10, 0x9f, 0x77, 0x33,
	0xf8, 0xf4, 0x9a, 0xec, 0x07, 0x84, 0x5e, 0x3a, 0xf1, 0x3b, 0xb4, 0xd9, 0x26, 0x56, 0xc2, 0xe9,
	0xa8, 0x0c, 0xf7, 0x66, 0xc6, 0xc7, 0x12, 0x72, 0x71, 0xcc, 0xca, 0x99, 0xa2, 0xc2, 0x07, 0x4d,
	0xed, 0x59, 0xab, 0xa8, 0x03, 0x42, 0x2f, 0xec, 0xe4, 0xeb, 0xfa, 0x12, 0xa2, 0xb8, 0xd3, 0x25,
	0xae, 0x4a, 0x98, 0xff, 0x55, 0x02, 0x1f, 0xa2, 0xee, 0x11, 0x48, 0xb8, 0x1c, 0xe3, 0xc9, 0x6d,
	0x39, 0x6f, 0x41, 0x42, 0x38, 0x68, 0x6a, 0xcf, 0x5e, 0xa5, 0x04, 0xd3, 0x60, 0x3c, 0x99, 0x10,
	0xaa, 0x03, 0xc8, 0x1c, 0x6d, 0x5d, 0xac, 0x8f, 0x9f, 0xa1, 0x6e, 0xf4, 0xd7, 0x0d, 0x34, 0xf2,
	0x2f, 0xed, 0xc9, 0x07, 0xd4, 0xbf, 0xde, 0x0f, 0x0f, 0x50, 0x57, 0x48, 0x28, 0x75, 0x42, 0x87,
	0x6a, 0x81, 0x6d, 0x64, 0xe6, 0x55, 0xe6, 0x98, 0x43, 0x63, 0xb4, 0x4d, 0xdb, 0x67, 0xcb, 0x49,
	0x2e, 0x21, 0x75, 0x3a, 0x9a, 0x53, 0x82, 0x1c, 0xa1, 0xde, 0x7a, 0x4f, 0xfc, 0x14, 0x99, 0xa7,
	0x6c, 0xa1, 0xb2, 0x7a, 0xe1, 0xa3, 0xa6, 0xf6, 0x1e, 0xae, 0x4a, 0x8f, 0x5f, 0x4c, 0x0e, 0x5e,
	0xbe, 0x9a, 0x12, 0xda, 0x12, 0xf8, 0x39, 0xea, 0x9e, 0x43, 0x5a, 0x31, 0x75, 0xe2, 0x56, 0x54,
	0x33, 0xa1, 0xfd, 0x7d, 0xe9, 0x1a, 0x3f, 0x96, 0xae, 0xf1, 0x73, 0xe9, 0x1a, 0xdf, 0x7e, 0xb9,
	0xf7, 0xa2, 0x4d, 0xf5, 0x4b, 0xed, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x46, 0x00, 0x52, 0x96,
	0xb2, 0x03, 0x00, 0x00,
}

func (m *SnapSyncReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapSyncReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapSyncReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Status) > 0 {
		for iNdEx := len(m.Status) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Status[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Locator) > 0 {
		for iNdEx := len(m.Locator) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locator[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.StateRoot != nil {
		{
			size, err := m.StateRoot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TargetBlock != nil {
		{
			size, err := m.TargetBlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SnapSyncRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SnapSyncRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SnapSyncRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Datas) > 0 {
		for iNdEx := len(m.Datas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Datas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Status) > 0 {
		for iNdEx := len(m.Status) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Status[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapsync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.StateRoot != nil {
		{
			size, err := m.StateRoot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TargetBlock != nil {
		{
			size, err := m.TargetBlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Locator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Locator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Locator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.StateRoot != nil {
		{
			size, err := m.StateRoot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapsync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TransferStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Total != 0 {
		i = encodeVarintSnapsync(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x20
	}
	if m.Num != 0 {
		i = encodeVarintSnapsync(dAtA, i, uint64(m.Num))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintSnapsync(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *TransferData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransferData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransferData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintSnapsync(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintSnapsync(dAtA []byte, offset int, v uint64) int {
	offset -= sovSnapsync(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SnapSyncReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TargetBlock != nil {
		l = m.TargetBlock.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.StateRoot != nil {
		l = m.StateRoot.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if len(m.Locator) > 0 {
		for _, e := range m.Locator {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if len(m.Status) > 0 {
		for _, e := range m.Status {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SnapSyncRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TargetBlock != nil {
		l = m.TargetBlock.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.StateRoot != nil {
		l = m.StateRoot.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if len(m.Status) > 0 {
		for _, e := range m.Status {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if len(m.Datas) > 0 {
		for _, e := range m.Datas {
			l = e.Size()
			n += 1 + l + sovSnapsync(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Locator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.StateRoot != nil {
		l = m.StateRoot.Size()
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TransferStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Start != 0 {
		n += 1 + sovSnapsync(uint64(m.Start))
	}
	if m.Num != 0 {
		n += 1 + sovSnapsync(uint64(m.Num))
	}
	if m.Total != 0 {
		n += 1 + sovSnapsync(uint64(m.Total))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TransferData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovSnapsync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSnapsync(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSnapsync(x uint64) (n int) {
	return sovSnapsync(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SnapSyncReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapSyncReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapSyncReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TargetBlock == nil {
				m.TargetBlock = &Hash{}
			}
			if err := m.TargetBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StateRoot == nil {
				m.StateRoot = &Hash{}
			}
			if err := m.StateRoot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locator = append(m.Locator, &Locator{})
			if err := m.Locator[len(m.Locator)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = append(m.Status, &TransferStatus{})
			if err := m.Status[len(m.Status)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SnapSyncRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SnapSyncRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SnapSyncRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TargetBlock == nil {
				m.TargetBlock = &Hash{}
			}
			if err := m.TargetBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StateRoot == nil {
				m.StateRoot = &Hash{}
			}
			if err := m.StateRoot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = append(m.Status, &TransferStatus{})
			if err := m.Status[len(m.Status)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Datas = append(m.Datas, &TransferData{})
			if err := m.Datas[len(m.Datas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Locator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Locator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Locator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &Hash{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StateRoot == nil {
				m.StateRoot = &Hash{}
			}
			if err := m.StateRoot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransferData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransferData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransferData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapsync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapsync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapsync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSnapsync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSnapsync(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSnapsync
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapsync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSnapsync
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSnapsync
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSnapsync
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSnapsync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSnapsync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSnapsync = fmt.Errorf("proto: unexpected end of group")
)
