package graph

import (
	"context"
	"errors"
	"fmt"
)

// END is a special constant used to represent the end node in the graph.
const END = "END"

var (
	// ErrEntryPointNotSet is returned when the entry point of the graph is not set.
	ErrEntryPointNotSet = errors.New("entry point not set")

	// ErrNodeNotFound is returned when a node is not found in the graph.
	ErrNodeNotFound = errors.New("node not found")

	// ErrNoOutgoingEdge is returned when no outgoing edge is found for a node.
	ErrNoOutgoingEdge = errors.New("no outgoing edge found for node")
)

type State map[string]interface{}

// Node represents a node in the message graph.
type NodeFunction func(ctx context.Context, name string, state State) (State, error)

type Node struct {
	// Name is the unique identifier for the node.
	Name string

	// Function is the function associated with the node.
	// It takes a context and a slice of MessageContent as input and returns a slice of MessageContent and an error.
	Function NodeFunction
}

// Edge represents an edge in the message graph.
type EdgeFunction func(ctx context.Context, name string, state State) string

type Edge struct {
	// From is the name of the node from which the edge originates.
	From string

	// To is the name of the node to which the edge points and is generated by the condition function.
	To EdgeFunction
}

// Graph represents a message graph.
type Graph struct {
	// nodes is a map of node names to their corresponding Node objects.
	nodes map[string]Node

	// edges is a slice of Edge objects representing the connections between nodes.
	edges []Edge

	// entryPoint is the name of the entry point node in the graph.
	entryPoint string

	options Config
}

// NewGraph creates a new instance of Graph.
func NewGraph(opts ...Option) *Graph {
	options := Config{}

	for _, opt := range opts {
		opt(&options)
	}

	return &Graph{
		nodes:   make(map[string]Node),
		options: options,
	}
}

// AddNode adds a new node to the message graph with the given name and function.
func (g *Graph) AddNode(name string, fn NodeFunction) {
	g.nodes[name] = Node{
		Name:     name,
		Function: fn,
	}
}

// AddEdge adds a new edge to the message graph between the "from" and "to" nodes.
func (g *Graph) AddEdge(from, to string) {
	g.edges = append(g.edges, Edge{
		From: from,
		To: func(_ context.Context, name string, state State) string {
			// direct edge doesn't have a condition function
			return to
		},
	})
}

// AddConditionalEdge adds a new conditional edge to the message graph between the "from" and the conditional "to" generated by the condition function.
func (g *Graph) AddConditionalEdge(from string, condition EdgeFunction) {
	g.edges = append(g.edges, Edge{
		From: from,
		To:   condition,
	})
}

// SetEntryPoint sets the entry point node name for the message graph.
func (g *Graph) SetEntryPoint(name string) {
	g.entryPoint = name
}

// Runnable represents a compiled message graph that can be invoked.
type Runnable struct {
	// graph is the underlying Graph object.
	graph *Graph
}

// Compile compiles the message graph and returns a Runnable instance.
// It returns an error if the entry point is not set.
func (g *Graph) Compile() (*Runnable, error) {
	if g.entryPoint == "" {
		return nil, ErrEntryPointNotSet
	}

	return &Runnable{
		graph: g,
	}, nil
}

// Invoke executes the compiled message graph with the given input messages.
// It returns the resulting messages and an error if any occurs during the execution.
// Invoke executes the compiled message graph with the given input messages.
// It returns the resulting messages and an error if any occurs during the execution.
func (r *Runnable) Invoke(ctx context.Context, state State) (State, error) {
	currentNode := r.graph.entryPoint

	for {
		if currentNode == END {
			break
		}

		node, ok := r.graph.nodes[currentNode]
		if !ok {
			return nil, fmt.Errorf("%w: %s", ErrNodeNotFound, currentNode)
		}

		graphOpts := r.graph.options

		if graphOpts.NodeStartHandler != nil {
			graphOpts.NodeStartHandler.NodeStart(ctx, currentNode, state)
		}

		var err error
		state, err = node.Function(ctx, node.Name, state)
		if graphOpts.NodeEndHandler != nil {
			graphOpts.NodeEndHandler.NodeEnd(ctx, currentNode, state)
		}
		if err != nil {
			return nil, fmt.Errorf("error in node %s: %w", currentNode, err)
		}

		foundNext := false
		for _, edge := range r.graph.edges {
			if edge.From == currentNode {
				if graphOpts.EdgeEntryHandler != nil {
					graphOpts.EdgeEntryHandler.EdgeEntry(ctx, edge.From, state)
				}
				nextNode := edge.To(ctx, edge.From, state)
				if graphOpts.EdgeExitHandler != nil {
					graphOpts.EdgeExitHandler.EdgeExit(ctx, edge.From, state, nextNode)
				}
				currentNode = nextNode
				foundNext = true
				break
			}
		}

		if !foundNext {
			return nil, fmt.Errorf("%w: %s", ErrNoOutgoingEdge, currentNode)
		}
	}

	return state, nil
}
